name = "OceWind"
uuid = "7f6142f7-f420-4e01-9a36-d63e65e99877"
authors = ["Gaspartcho <g.deremble@laposte.net>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"
